### ISSUE TITLE
Ios Exception

### ISSUE THREAD

**Issue by geekmuhannad** [TimmyRB/snapkit#21]
Hi
I tried to share an image with Snapchat
it works in android but I got an exception in ios 

I already add user demo & bundle id

[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(SendMediaSendError, Optional(Error Domain=SCSDKCreativeKitErrorDomain Code=10 "error_description_malformed_url" UserInfo={NSLocalizedRecoverySuggestion=recovery_suggestion_check_documentation, NSLocalizedDescription=error_description_malformed_url, NSLocalizedFailureReason=}), null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      Snapkit.share (package:snapkit/snapkit.dart:193:5)
<asynchronous suspension>

**Comment by geekmuhannad** [comment]
The problem from the image provider.
why in android accept sharing images from file but ios gave an exception as showing above

`  snapkit.share(SnapchatMediaType.PHOTO,
                        image: Image.file(
                          imageFile
                        ).image,
                        sticker: SnapchatSticker(
                          image:
                              AssetImage("assets/images/shared_sarahah_ar.png"),
                        ),
                        attachmentUrl: Constants.sarahahUrl);`

**Comment by TimmyRB** [comment]
Sorry for the delay, have you tried loading the image the same way you're loading the Sticker's Image ie thru `AssetImage("path/to/image.png")` ?

**Comment by gkmuhannad** [comment]
Thanks, it works very well
