### ISSUE TITLE
TestFlight problem

### ISSUE THREAD

**Issue by gkmuhannad** [TimmyRB/snapkit#24]
Hello,
sharing to snap as stickers in IOS is working fine in debug and release mode but after upload the app to 
Test Flight and tried to share SnapChat  the app crashed.

is there any way to find the problem ?

**Comment by gkmuhannad** [comment]
Uploading RPReplay_Final1632739809.MP4…

**Comment by gkmuhannad** [comment]
https://user-images.githubusercontent.com/80851543/134895208-a91816d3-1672-4b62-9b2a-d0b7889fe2ee.MP4

**Comment by TimmyRB** [comment]
Hi! Has your Snapchat application been approved by Snapchat on the [Snap Developer Portal](https://kit.snapchat.com/manage)? You can only use the Staging key on unreleased versions of your app.

**Comment by gkmuhannad** [comment]
yes it is approved, 

and the android version works fine. 

I tried to run on my iPhone as a release mode it works fine but not working in testflight

**Comment by gkmuhannad** [comment]
when I was using the old MacBook it was working good, but know I am using the new MacBook M1.

**Comment by hennonoman** [comment]
I tried to build the IOS version with old mac but still the same problem.

**Comment by gkmuhannad** [comment]
I tried to build the IOS version with old mac but still the same problem

**Comment by TimmyRB** [comment]
I'm not able to diagnose your problem if you don't provide anything. Please include your `Android manifest.xml`, your `Info.plist` and the relevant code that is crashing Snapchat.

**Comment by gkmuhannad** [comment]
AndroidManifest.xml 
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"

    package="com.app.sarahahgift">
    
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />


    <application
        android:name=".Application"
        android:label="@string/app_name"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
        android:hardwareAccelerated="true"
        android:icon="@mipmap/ic_launcher_foreground">


        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                
                <data
                    android:host="*.sarahah.com"
                    android:scheme="https"
                    />

                        </intent-filter>
                <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                
                <data
                    android:scheme="sarahah"
                    android:host="*" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.LAUNCHER" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="com.app.sarahahgift" />
            </intent-filter>


        </activity>


        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="high_importance_channel" />


        <meta-data
            android:name="com.snapchat.kit.sdk.clientId"
            android:value="65a7d454-d828-4a66-9b08-9846f3658870" />


        <meta-data
            android:name="com.snapchat.kit.sdk.scopes"
            android:resource="@array/snap_connect_scopes" />

        <activity
            android:name="com.snapchat.kit.sdk.SnapKitActivity"
            android:launchMode="singleTask">

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                
                <data
                    android:scheme="sarahah"
                    android:host="snapchat"
                    android:path="/oauth2" />
            </intent-filter>




        </activity>










        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />

        <provider
            android:name="com.facebook.FacebookContentProvider"
            android:authorities="com.facebook.app.FacebookContentProvider[facebook_app_id]"
            android:exported="false" />
        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>


        <receiver
            android:name=".CheckoutBroadcastReceiver"
            android:exported="false" />

        <service
            android:name="com.oppwa.mobile.connect.service.ConnectService"
            android:exported="false" />

        <activity
            android:name="com.oppwa.mobile.connect.checkout.dialog.CheckoutActivity"
            android:configChanges="orientation"
            android:exported="false"
            android:launchMode="singleTop"
            android:theme="@style/Theme.Checkout.Light"
            android:windowSoftInputMode="adjustPan"
            tools:replace="android:windowSoftInputMode"
            />
    </application>
</manifest>
`



*note: the android version works fine

**Comment by gkmuhannad** [comment]
info.pilst

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleLocalizations</key>
	<array>
		<string>ar</string>
		<string>en</string>
	</array>
	<key>CFBundleName</key>
	<string>Sarahah</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>app.sarahah.com</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.sarahah.ios</string>
				<string>com.googleusercontent.apps.248219105226-t2dmf6216e0m94j03hg69s37drgk8ajf</string>
				<string>sarahah</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>FacebookAppID</key>
	<string>facebookid</string>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>https</string>
		<string>http</string>
		<string>whatsapp</string>
		<string>fbapi</string>
		<string>fbauth</string>
		<string>fbauth2</string>
		<string>fbshareextension</string>
		<string>fbapi20130214</string>
		<string>fbapi20130410</string>
		<string>fbapi20130702</string>
		<string>fbapi20131010</string>
		<string>fbapi20131219</string>
		<string>fbapi20140410</string>
		<string>fbapi20140116</string>
		<string>fbapi20150313</string>
		<string>fbapi20150629</string>
		<string>fbapi20160328</string>
		<string>fb-messenger-share-api</string>
		<string>instagram-stories</string>
		<string>facebook-stories</string>
		<string>facebook</string>
		<string>instagram</string>
		<string>twitter</string>
		<string>tw</string>
		<string>telegram</string>
		<string>tg</string>
		<string>snapchat</string>
		<string>bitmoji-sdk</string>
		<string>itms-apps</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsArbitraryLoadsForMedia</key>
		<true/>
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>To take a picture for your profile photo</string>
	<key>NSContactsUsageDescription</key>
	<string>To show you contacts who are registered in Sarahah</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>To record a voice message</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>To upload a profile photo</string>
	<key>SCSDKClientId</key>
	<string>I remove it from here just for privacy</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIRequiresFullScreen</key>
	<true/>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>applinks:*.sarahah.com</string>
		<string>applinks:sarahah.com</string>
		<string>applinks:sarahah.page.link</string>
	</array>
</dict>
</plist>
`

**Comment by gkmuhannad** [comment]
this the code for the IOS

```
snapkit.share(SnapchatMediaType.NONE,
                                    sticker: SnapchatSticker(
                                        image: FileImage(File(imagePath))),
                                    caption: "",
                                    attachmentUrl: url)
```

**Comment by TimmyRB** [comment]
A few things make sure the ClientId in your `AndroidManifest.xml` matches the on in your `Info.plist` and please edit your comment to include more relevant code ie where both `imagePath` and `url` get set.

**Comment by gkmuhannad** [comment]
Hi,
I edit the code in the above comment ,

yes my friend i am sure the client Id is the same

**Comment by geekmuhannad** [comment]
Hi,

I share the problem with snapchat team, they said the problem resolved with the new update of the app 11.48

thanks my friend, the code is working now with new update of snapchat

![Screen Shot 1443-02-28 at 11 02 03 AM](https://user-images.githubusercontent.com/85584023/135984234-73d2c125-496a-4ec0-a94b-19789ce2bc97.png)

**Comment by gkmuhannad** [comment]
Hi,

I share the problem with snapchat team, they said the problem resolved with the new update of the app 11.48

thanks my friend, the code is working now with new update of snapchat
![Screen Shot 1443-02-28 at 11 02 03 AM](https://user-images.githubusercontent.com/80851543/135984530-1054a27b-6375-47a5-8cd3-bd8a1d6d398f.png)

**Comment by atif2148** [comment]
> yes it is approved,
> 
> and the android version works fine.
> 
> I tried to run on my iPhone as a release mode it works fine but not working in testflight

@gkmuhannad is sticker showing while sharing it to snapchat?

**Comment by gkmuhannad** [comment]
yes it works for me, the problem was from Snapchat

**Comment by atif2148** [comment]
> yes it works for me, the problem was from Snapchat

Is your sticker showing in snapchat in android because i can see the link but not sticker when sharing. 
Any help would be appreciated.
Thanks
