### ISSUE TITLE
Stickers on Android

### ISSUE THREAD

**Issue by TimmyRB** [TimmyRB/snapkit#3]
There is an issue where Sticker images don't always appear on the Snapchat app on Android, this is being looked into.

**Comment by atif2148** [comment]
> There is an issue where Sticker images don't always appear on the Snapchat app on Android, this is being looked into.

Hey, @TimmyRB do you have any update on the sticker now showing in the Snapchat app?
I need to deliver my app to the client and it's very urgent.
Any help would be appreciated.
