### ISSUE TITLE
On snapchat app its showing `Something went wrong` 

### ISSUE THREAD

**Issue by arslankaleem7229** [TimmyRB/snapkit#36]
I have resolved some of the issues related to snapchat but now there is following problem.

> When I click on Login with snapchat button from example project it navigates to app and app says `Something went wrong` and when I perform same thing 5-6 times then it will redirect to web and from there everything works

> For Android everything works well from web but from app it shows error

> For IOS even from web it says `Safari cannot open the page because the address is invalid`

**Comment by thang510023** [comment]
I also face this problem

**Comment by Bwolfs2** [comment]
Any Solution?

**Comment by arslankaleem7229** [comment]
Yes, I have seen that in documentation its not clear how to deeplink so I have searched a bit and added following lines in app which helped resolved my problem

> For IOS

```
                <key>FlutterDeepLinkingEnabled</key>
		<true/>
```

> For Android 

```
<meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
```
