### ISSUE TITLE
Can't run build - Undefined symbol: _OBJC_CLASS_$_SCSDKLoginClient

### ISSUE THREAD

**Issue by simplenotezy** [TimmyRB/snapkit#46]
All of a sudden I can't run the build anymore - it worked fine yesterday, and we even released this version to TestFlight and it works fine, however, today when I try to run the client locally, I am getting this error:

`Undefined symbol: _OBJC_CLASS_$_SCSDKLoginClient`

<img width="479" alt="image" src="https://user-images.githubusercontent.com/3786627/207914434-30c112b8-d436-4e00-8b81-f4b308595325.png">

I have tried running flutter clean, pod install and restarting the devices, but no luck.

**Comment by simplenotezy** [comment]
I fixed it by modifying my Podfile, adding `config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"`, like so:

```diff
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
+      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
```

**Comment by AndrewPiterov** [comment]
@simplenotezy thanks, it works. In my case before it was running on real device iPhone 7 iOS 15.3, but not on emulator iPhone 14 iOS 16.1.

**Comment by simplenotezy** [comment]
> @simplenotezy thanks, it works. In my case before it was running on real device iPhone 7 iOS 15.3, but not on emulator iPhone 14 iOS 16.1. 

Yup - same here!
