### ISSUE TITLE
Not loading image

### ISSUE THREAD

**Issue by Saurabh-Detharia** [TimmyRB/snapkit#5]
Running on iOS, opens Snapchat, but couldn't launch the image which passed. As well, no error is thrown, only shows "Something went wrong, Please try again later".

**Comment by TimmyRB** [comment]
When creating an issue, make sure to follow the provided templates, to be able to debug an issue like yours I need

- [ ] Relevant code
- [ ] Your snapkit config on the [Snapchat Developer Portal](https://kit.snapchat.com/manage/) (Make sure to block out your OAuth2 Client ID)
- [ ] Your snapkit config in `Info.plist` (Make sure to block out your OAuth2 Client ID)

**Comment by Saurabh-Detharia** [comment]
Here is the info.plist

```
<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>instagram-stories</string>
		<string>fb</string>
		<string>facebook</string>
		<string>facebook-stories</string>
		<string>instagram</string>
		<string>twitter</string>
		<string>whatsapp</string>
		<string>tg</string>
		<string>snapchat</string>
		<string>fb-messenger</string>
	</array>
        <key>NSPhotoLibraryUsageDescription</key>
	<string>The app need to access Storage to save video in gallery.</string>
        <key>SCSDKClientId</key>
	<string>93fa870c-b94f-46b9-87f4-c7b43b177eff</string>
	<key>SnapKitAutoInit</key>
	<false/>
```

Here is the function I am using. I am downloading on image and trying to pass it's path in the function.

```
public func shareToSnapchat(imagePath: String) {
        let fileUrl = URL(fileURLWithPath: imagePath)
        
        let photo = SCSDKSnapPhoto(imageUrl: fileUrl)
        let snap = SCSDKPhotoSnapContent(snapPhoto: photo)
//        snap.caption = "Test text"
//        snap.attachmentUrl = "https://www.snapchat.com"
        let api = SCSDKSnapAPI(content: snap)
        api.startSnapping { error in

            if let error = error {
                print(error.localizedDescription)
            } else {
                // success

            }
        }
        
    }
```
Let me know if still I miss anything.

**Comment by TimmyRB** [comment]
This repository is only for the Flutter Plugin snapkit available [here](https://pub.dev/packages/snapkit), not for Snapchat's iOS SDK. You can try contacting Snapchat if you need help with their SDK.

**Comment by Saurabh-Detharia** [comment]
I have tried below method as well. But I am getting the error. 

Error: 
Unhandled Exception: PlatformException(SendMediaSendError, Optional(Error Domain=SCSDKCreativeKitErrorDomain Code=11 "error_description_missing_data" UserInfo={NSLocalizedRecoverySuggestion=Please check documentation for potential mistakes. Please content snapkit-support@snap.com if problem persists., NSLocalizedDescription=error_description_missing_data, NSLocalizedFailureReason=}), null, null)

Code:
```
snapkit.share(SnapchatMediaType.VIDEO,
              videoUrl: File(videoPath).path,
              caption: "Hello");
```

videoPath is the file path of downloaded video's path. Which I get using below way.
```
final dir =  Platform.isAndroid ? await getExternalStorageDirectory() : await getApplicationDocumentsDirectory();
String path = dir!.path + "/"+ videoUrl.split("/").last;
return File(path);
```
I am getting below path once download is completed. 
/var/mobile/Containers/Data/Application/A94EC0D4-AA4D-4982-AAFE-16F17CD3E4BE/Documents/media-cBeAwVzxxcqzvsB4eEKXg.mp4

What exactly I need to pass in the videoUrl param?

**Comment by Saurabh-Detharia** [comment]
Hi Jacob!

I have tried the plugin and am facing some issues as well. I have added
comments to the same issue. Can you help me out to fix and make it work?
Thanks in advance.

**Comment by TimmyRB** [comment]
The `videoUrl` parameter has to be a `String` that contains an external url eg. `https://domain.com/video.mp4`, and if you're using the same `Info.plist` as you posted before, be sure to remove the line
```xml
<key>SnapKitAutoInit</key>
<false/>
```
and follow the iOS steps available on the Wiki [here](https://github.com/TimmyRB/snapkit/wiki/iOS-Installation#infoplist)

**Comment by Saurabh-Detharia** [comment]
I have updated my code with below snippet and please also check the updated info.plist. 

```
snapkit.share(SnapchatMediaType.VIDEO,
                            videoUrl: "https://dhq5cswx9ekww.cloudfront.net/1d4aa042-be42-40ac-90cc-81cbb91bdf16/MP4Download/media-GI2ZKJLnjKPuWzSfc6DDK.mp4",
                            caption: "Hello");
```

info.plist

```
        <key>LSApplicationQueriesSchemes</key>
	<array>
		<string>snapchat</string>
         </array>

         <array>
		<string>snapchat</string>
		<string>bitmoji-sdk</string>
		<string>itms-apps</string>
	</array>
	
	<key>SCSDKClientId</key>
	<string>538a1ef6-2ea9-4f83-92d8-07414ee97f0d</string>

	<key>SCSDKScopes</key>
	<array>
		<string>https://auth.snapchat.com/oauth2/api/user.bitmoji.avatar</string>
		<string>https://auth.snapchat.com/oauth2/api/user.display_name</string>
		<string>https://auth.snapchat.com/oauth2/api/user.external_id</string>
	</array>

```

When I tried to share below url, it work fine for 3 - 4 times then it shows "Something went wrong." error when Snapchat opens.
1. http://techslides.com/demos/sample-videos/small.mp4

Below video urls are not working and throwing below error.
1. https://assets.mixkit.co/videos/preview/mixkit-daytime-city-traffic-aerial-view-56-large.mp4
2. https://assets.mixkit.co/videos/preview/mixkit-a-girl-blowing-a-bubble-gum-at-an-amusement-park-1226-large.mp4
3. https://dhq5cswx9ekww.cloudfront.net/1d4aa042-be42-40ac-90cc-81cbb91bdf16/MP4Download/media-GI2ZKJLnjKPuWzSfc6DDK.mp4

```
Runner[18924:9866810] [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(SendMediaSendError, Optional(Error Domain=SCSDKCreativeKitErrorDomain Code=8 "error_invalid_file_format" UserInfo={NSLocalizedRecoverySuggestion=Please check documentation for potential mistakes. Please content snapkit-support@snap.com if problem persists., NSLocalizedDescription=error_invalid_file_format, NSLocalizedFailureReason=}), null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      Snapkit.share (package:snapkit/snapkit.dart:172:5)
<asynchronous suspension>
```

**Comment by TimmyRB** [comment]
Thanks for bringing this to my attention, it looks like there are some bugs and errors in Snapchat's iOS SDK that need to be fixed or at least provide a better error response. I'll be looking into this and seeing if can find a suitable workaround, I'll update this if I find anything or fix the bug.

**Comment by Saurabh-Detharia** [comment]
Either it is url length issue or any video file regarding issue? If you can update the reason of the error, I can try put workaround for it, until the issue get fixed.

**Comment by Saurabh-Detharia** [comment]
@TimmyRB Any update on this?

**Comment by TimmyRB** [comment]
@Saurabh-Detharia sorry for the delay, I've been quite busy recently. Don't worry though, a fix is still being worked on!

**Comment by Saurabh-Detharia** [comment]
@TimmyRB Any update on this?

**Comment by TimmyRB** [comment]
I will update this when there has been a major update, if you need a solution sooner you can try to read snapchat's documentation and implement it yourself in a pull request and I'll take a look.
